# Config :P 
options:
  enableActionbar: true
  enableDyes: false
  enableItemSwitchMessage: false
  enableJoinMessage: true
  enableOffHand: false
  enableWorldToggleMessage: false
  enableWorldSwitchMessage: false
  toggleCooldown: 10

# Put The Name Of The Worlds If You Want It Multi-World
# Dont Delete The " "
enabled-Worlds:
  - "world"
  - "world 1"
  - "world 2"

item:
  slot: 2
  on:
    item: "LIME_DYE"
    dye: "LIME"
    name: "&7Players are &aon!"
    lore:
      - "&7Toggle Player Visibility To &cOff"
  off:
    item: "GRAY_DYE"
    dye: "GRAY"
    name: "&7Players Are Now &cOff!"
    lore:
      - "&7Toggle Player Visibility To &aOn"
messages:
  prefix: "&9Visibility > "
  toggle:
    on:  "&a-Players On!"
    off: "&c-Players Off!"
    already:
      on:  "&aAlready On!"
      off: "&cAlready Off!"
  permission: "&cYou don't have the permissions to do that. &c[!] This Is A Problem Please Contact &9Durpy &c[!]"
  toggleCooldown: "&cWow So Fast, &7Please Wait &e%time%&7 Second(s) Before Toggling Again. ;)"
  world: "&cYou Can't Use This Here."
