# Config :P 
options:
  enableActionbar: true
  enableDyes: false
  enableItemSwitchMessage: false
  enableJoinMessage: true
  enableOffHand: false
  enableWorldToggleMessage: false
  enableWorldSwitchMessage: false
  toggleCooldown: 10

# Put The Name Of The Worlds If You Want It Multi-World
# Dont Delete The " "
enabled-Worlds:
  - "world"
  - "world 1"
  - "world 2"
